# Generated by Django 5.2.7 on 2025-11-05 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_repairrequest_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='estimated_cost',
        ),
        migrations.AddField(
            model_name='estimation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='estimation',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='estimation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Estimationitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.estimation')),
            ],
        ),
    ]
