# Generated by Django 5.2.7 on 2025-11-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_estimation_estimated_cost_estimation_subtotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimationitems',
            old_name='Estimation',
            new_name='estimation',
        ),
    ]
