# Generated by Django 5.2.7 on 2025-11-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_repairrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updaterepairstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('update_status', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('REPAIRING', 'REPAIRING'), ('TESTING', 'TESTING'), ('READY TO DELIVER', 'READY TO DELIVER')], default='PENDING', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repairrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.repairrequest')),
            ],
        ),
    ]
