# Generated by Django 5.2.7 on 2025-11-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_updaterepairstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Updaterepairstatus',
        ),
    ]
