# Generated by Django 5.2.7 on 2025-11-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_repairrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
