# Generated by Django 5.2.7 on 2025-11-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='generated_at',
            new_name='generated_on',
        ),
    ]
