# Generated by Django 5.2.7 on 2025-11-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_rename_generated_at_invoice_generated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='authorized_signatory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
