# Generated by Django 5.2.7 on 2025-11-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_invoice_authorized_signatory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='authorized_signatory',
        ),
    ]
