# Generated by Django 5.2.7 on 2025-12-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='phone',
        ),
    ]
