# Generated by Django 5.2.7 on 2025-12-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_remove_companyprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
