# Generated by Django 5.2.7 on 2025-12-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_remove_companyprofile_email_companyprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
