# Generated by Django 5.2.7 on 2025-12-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_companyprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(default='Vividobots', max_length=200),
            preserve_default=False,
        ),
    ]
