# Generated by Django 5.2.7 on 2025-12-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_companyprofile_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='name',
            new_name='owner_name',
        ),
    ]
