# Generated by Django 5.2.7 on 2025-12-09 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterepairstatus',
            name='description',
            field=models.CharField(default='Initial status update', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updaterepairstatus',
            name='updated_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updaterepairstatus',
            name='update_status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('REPAIRING', 'REPAIRING'), ('TESTING', 'TESTING'), ('READY_TO_DELIVER', 'READY_TO_DELIVER')], default='PENDING', max_length=50),
        ),
    ]
