# Generated by Django 5.2.7 on 2025-12-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_updaterepairstatus_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterepairstatus',
            name='update_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('REPAIRING', 'REPAIRING'), ('TESTING', 'TESTING'), ('READY_TO_DELIVER', 'READY_TO_DELIVER')], default='PENDING', max_length=50),
        ),
    ]
