# Generated by Django 5.2.7 on 2025-12-10 06:16

import builtins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_alter_updaterepairstatus_update_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updaterepairstatus',
            options={'ordering': ['updated_on', builtins.id]},
        ),
        migrations.RemoveField(
            model_name='updaterepairstatus',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='updaterepairstatus',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='updaterepairstatus',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='updaterepairstatus',
            name='repairrequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='service.repairrequest'),
        ),
        migrations.AlterField(
            model_name='updaterepairstatus',
            name='update_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('REPAIRING', 'REPAIRING'), ('TESTING', 'TESTING'), ('READY_TO_DELIVER', 'READY_TO_DELIVER')], max_length=50),
        ),
    ]
