# Generated by Django 5.2.7 on 2025-12-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_alter_updaterepairstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updaterepairstatus',
            options={'ordering': ['updated_on', 'id']},
        ),
    ]
