# Generated by Django 5.2.7 on 2025-12-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_alter_updaterepairstatus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterepairstatus',
            name='update_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('REPAIRING', 'REPAIRING'), ('TESTING', 'TESTING'), ('READY_TO_DELIVER', 'READY_TO_DELIVER'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=50),
        ),
    ]
