# Generated by Django 5.2.7 on 2025-12-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_repairrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='authorized_signature',
            field=models.ImageField(blank=True, null=True, upload_to='company/signatures/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='seal',
            field=models.ImageField(blank=True, null=True, upload_to='company/seals/'),
        ),
    ]
