# Generated by Django 5.2.7 on 2026-01-08 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0042_passwordresetotp_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
