# Generated by Django 5.2.7 on 2026-01-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0043_estimation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
