# Generated by Django 5.2.7 on 2026-01-10 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0045_alter_estimation_repair_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations', to='service.invoice'),
        ),
    ]
