# Generated by Django 5.2.7 on 2026-02-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0047_alter_repairrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_APPROVAL', 'WAITING_FOR_APPROVAL'), ('STARTED', 'STARTED'), ('REPAIRING', 'REPAIRING'), ('TESTING', 'TESTING'), ('READY_TO_DELIVER', 'READY_TO_DELIVER')], default='WAITING_FOR_APPROVAL', max_length=30),
        ),
    ]
