# Generated by Django 5.2.7 on 2026-02-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0048_estimation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='ready_to_deliver_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='repairing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='started_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='testing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
