# Generated by Django 5.2.7 on 2026-02-07 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0049_estimation_ready_to_deliver_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterepairstatus',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='service.estimation'),
        ),
    ]
