# Generated by Django 5.2.7 on 2026-02-09 08:38

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('service', '0051_invoice_estimation_alter_invoice_repair_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='service.estimation'),
        ),
    ]
