# Generated by Django 5.2.7 on 2026-02-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0052_remove_estimation_invoice_alter_invoice_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='estimation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='service.estimation'),
        ),
    ]
