# Generated by Django 5.2.7 on 2026-07-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0054_estimationitems_created_at_alter_invoice_estimation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimationitems',
            name='created_at',
        ),
    ]
