# Generated by Django 5.2.7 on 2026-07-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0055_remove_estimationitems_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='requires_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_APPROVAL', 'WAITING_FOR_APPROVAL'), ('STARTED', 'STARTED'), ('REPAIRING', 'REPAIRING'), ('TESTING', 'TESTING'), ('READY_TO_DELIVER', 'READY_TO_DELIVER'), ('INVOICED', 'INVOICED')], default='WAITING_FOR_APPROVAL', max_length=30),
        ),
    ]
